cornerConnectionCells = [
    ['W1', 'B3', 'R7'],
    ['W3', 'R5', 'G1'],
    ['W5', 'G7', 'O3'],
    ['W7', 'O1', 'B5'],
    ['Y1', 'B7', 'O7'],
    ['Y3', 'O5', 'G5'],
    ['Y5', 'R3', 'G3'],
    ['Y7', 'B1', 'R1'],
]

edgeConnectionDict = {
    'WR' : 'W2',
    'RW' : 'R6',
    'WG' : 'W4',
    'GW' : 'G8',
    'WO' : 'W6',
    'OW' : 'O2',
    'WB' : 'W8',
    'BW' : 'B4',
    'YO' : 'Y2',
    'OY' : 'O6',
    'YG' : 'Y4',
    'GY' : 'G4',
    'YR' : 'Y6',
    'RY' : 'R2',
    'YB' : 'Y8',
    'BY' : 'B8',
    'BR' : 'B2',
    'RB' : 'R8',
    'RG' : 'R4',
    'GR' : 'G2',
    'GO' : 'G6',
    'OG' : 'O4',
    'OB' : 'O8',
    'BO' : 'B6'
}

cornerConnectionDict = {
    'WBR' : 'W1',
    'WRB' : 'W1',
    'BWR' : 'B3',
    'BRW' : 'B3',
    'RBW' : 'R7',
    'RWB' : 'R7',
    'WRG' : 'W3',
    'WGR' : 'W3',
    'RWG' : 'R5',
    'RGW' : 'R5',
    'GRW' : 'G1',
    'GWR' : 'G1',
    'WGO' : 'W5',
    'WOG' : 'W5',
    'GWO' : 'G7',
    'GOW' : 'G7',
    'OGW' : 'O3',
    'OWG' : 'O3',
    'WOB' : 'W7',
    'WBO' : 'W7',
    'OWB' : 'O1',
    'OBW' : 'O1',
    'BOW' : 'B5',
    'BWO' : 'B5',
    'YBO' : 'Y1',
    'YOB' : 'Y1',
    'BYO' : 'B7',
    'BOY' : 'B7',
    'OBY' : 'O7',
    'OYB' : 'O7',
    'YOG' : 'Y3',
    'YGO' : 'Y3',
    'OYG' : 'O5',
    'OGY' : 'O5',
    'GOY' : 'G5',
    'GYO' : 'G5',
    'YRG' : 'Y5',
    'YGR' : 'Y5',
    'RYG' : 'R3',
    'RGY' : 'R3',
    'GRY' : 'G3',
    'GYR' : 'G3',
    'YBR' : 'Y7',
    'YRB' : 'Y7',
    'BYR' : 'B1',
    'BRY' : 'B1',
    'RBY' : 'R1',
    'RYB' : 'R1'
}

edgeConnectionCells = [
    ['W2', 'R6'],
    ['W4', 'G8'],
    ['W6', 'O2'],
    ['W8', 'B4'],
    ['Y2', 'O6'],
    ['Y4', 'G4'],
    ['Y6', 'R2'],
    ['Y8', 'B8'],
    ['B2', 'R8'],
    ['R4', 'G2'],
    ['G6', 'O4'],
    ['O8', 'B6'],
]

cornerConnectionColors = [
    ['W', 'B', 'R'],
    ['W', 'R', 'G'],
    ['W', 'G', 'O'],
    ['W', 'O', 'B'],
    ['Y', 'B', 'O'],
    ['Y', 'O', 'G'],
    ['Y', 'R', 'G'],
    ['Y', 'B', 'R'],
]

edgeConnectionColors = [
    ['W', 'R'],
    ['W', 'G'],
    ['W', 'O'],
    ['W', 'B'],
    ['Y', 'O'],
    ['Y', 'G'],
    ['Y', 'R'],
    ['Y', 'B'],
    ['B', 'R'],
    ['R', 'G'],
    ['G', 'O'],
    ['O', 'B'],
]

